{"name": "test_accept_order_with_wrong_courier_id_failed", "status": "passed", "start": 1726089016988, "stop": 1726089044272, "uuid": "34a55639-a997-4839-a682-9ad6d6117709", "historyId": "1e8b653893fdf299af49e3fc54183cfc", "testCaseId": "1e8b653893fdf299af49e3fc54183cfc", "fullName": "tests.test_accept_order_endpoint.TestAcceptOrder#test_accept_order_with_wrong_courier_id_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order_endpoint"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "HOME"}, {"name": "thread", "value": "17600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order_endpoint"}]}